CREATE DATABASE linkey;
USE linkey;

CREATE TABLE tbl_dadosfuncionarios 
(
Id_Func INT NOT NULL AUTO_INCREMENT UNIQUE,
Nome VARCHAR(100) NOT NULL,
RG VARCHAR(20) NOT NULL UNIQUE,
CPF VARCHAR(20) NOT NULL UNIQUE,
Nascimento VARCHAR(10) NOT NULL,
Sexo VARCHAR (15) NOT NULL,
Telefone VARCHAR(20),
Celular VARCHAR(20),
Email VARCHAR(100) NOT NULL UNIQUE,
CEP VARCHAR(20) NOT NULL,
Endereço VARCHAR(100) NOT NULL,
Numero INT(10) NOT NULL,
Complemento VARCHAR(45),
Cidade VARCHAR(50) NOT NULL,
Bairro VARCHAR(50) NOT NULL,
UF VARCHAR(2) NOT NULL,	
PRIMARY KEY (Id_Func)
)
ENGINE = INNODB DEFAULT CHARSET = UTF8;

CREATE TABLE tbl_clientes 
(
Cod_Cliente INT NOT NULL AUTO_INCREMENT,
Nome VARCHAR(100) NOT NULL,
Sexo VARCHAR(15) NOT NULL,
RG VARCHAR(20) NOT NULL UNIQUE,
CPF VARCHAR(20) NOT NULL UNIQUE,
Telefone VARCHAR(20) NOT NULL,
Celular VARCHAR(20),
Email VARCHAR(100) NOT NULL UNIQUE,
Endereço VARCHAR(100) NOT NULL,
Bairro VARCHAR(50) NOT NULL,
UF VARCHAR(2) NOT NULL,
PRIMARY KEY (Cod_Cliente)
)
ENGINE = INNODB DEFAULT CHARSET = UTF8;

CREATE TABLE tbl_financeiro 
(
RF VARCHAR(20) NOT NULL UNIQUE,					 
Cargo_Funcionario VARCHAR(100) NOT NULL,
Salario_Funcionario VARCHAR(30) NOT NULL,
Data_Adimissao VARCHAR(20) NOT NULL,
Data_Demissao VARCHAR(20),
Id_Func INT NOT NULL,
PRIMARY KEY (RF), 
CONSTRAINT fkfuncionario_financeiro FOREIGN KEY (Id_Func) 
REFERENCES tbl_dadosfuncionarios (Id_Func)
)
ENGINE = INNODB DEFAULT CHARSET = UTF8;

CREATE TABLE tbl_loginfuncionarios
(
Cod_login INT NOT NULL AUTO_INCREMENT,
Senha VARCHAR(10) NOT NULL,
RF VARCHAR(20) NOT NULL,
PRIMARY KEY (Cod_login),
CONSTRAINT fkfinanceiro_login FOREIGN KEY (RF) 
REFERENCES tbl_financeiro (RF)
)
ENGINE = INNODB DEFAULT CHARSET = UTF8;

CREATE TABLE tbl_Veiculos
(
Id_Veic INT NOT NULL AUTO_INCREMENT,
Id_Func INT,
Veiculo VARCHAR(50) NOT NULL,
Placa VARCHAR(8) UNIQUE NOT NULL,
Ano INT(4) NOT NULL,
Marca VARCHAR(30) NOT NULL,
Modelo VARCHAR(100),
Chassi VARCHAR(150),
Quantidade INT NOT NULL,
PRIMARY KEY (Id_Veic),
CONSTRAINT fk_veiculo_funcionario FOREIGN KEY (Id_Func) 
REFERENCES tbl_dadosfuncionarios (Id_Func)
)
ENGINE = INNODB DEFAULT CHARSET = UTF8;